### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by pingwes** [OpenwaterHealth/opw_ustx#1]
Step 3 says: 

"Import Project: embedded/ustx_cpp/ustxtest"

However there is no ustx_cpp subdirectory in embedded.

**Comment by georgevigelette** [comment]
I believe the readme needs to be modified everything is contained within this repository.  If you clone the repository with     , you will find the STM32 embedded firmware located in the embedded folder and the Host CPP application under application.  You can open and compile the CPP application with Visual Studio Community Edition by opening the solution file located in opw_ustx\application\ustx-onda\msvc.  For the embedded firmware you can open and compile that software with the STM32 IDE opening the project from file located at opw_ustx\embedded.  Let me know if you have an further issues and we will be sure to update the readme.
